# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-15 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancleHf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CancelId', models.CharField(default='0_0', max_length=128, unique=True, verbose_name='取关编号')),
                ('userid', models.IntegerField(default=0, verbose_name='被取关用户')),
                ('cancle_id', models.IntegerField(default=0, verbose_name='取关用户')),
                ('cancel_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取关时间')),
            ],
        ),
        migrations.CreateModel(
            name='HufenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HufenId', models.CharField(default='0_0', max_length=128, unique=True, verbose_name='互粉编号')),
                ('user1', models.IntegerField(default=0, verbose_name='用户1')),
                ('user2', models.IntegerField(default=0, verbose_name='用户2')),
                ('state', models.IntegerField(default=0, verbose_name='匹配状态')),
                ('bguser', models.IntegerField(default=0, verbose_name='背锅用户')),
                ('errinfo', models.CharField(default='NoError', max_length=256, verbose_name='异常信息')),
                ('hftime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='互粉时间')),
            ],
        ),
    ]
